### ISSUE TITLE
По файлу конфигурации

### ISSUE THREAD

**Issue by iproha94** [iproha94/javaClickerLite#10]
Не уверен, что должен быть синглтоном. Думаю возможна ситуация, когда в одном мейне запускаем несколько серверов, на разных урлах. 
Также путь к файлу пропертис нужно наверно передавать в класс конфигурации при его создании, а не хардкодить статически в нем же. Так мы сможем из мэйна создавать разные объекты конфигурации с разными параметрами, взятые из разных файлов. 
Поля желательно заанотировать нотналом.
 Не очень  понимаю, почему генерятся исключения, и не указывается, что они пробрасываться наверху в сигнатуре метода, в котором оно генерится.  
Возможно не нужно наверх кидать исключения, а если не удается прочитать нужный параметр из файла пропертис, то задавать значение по дефолту какое нибудь. Так мы сможем и без файла пропертис запускать сервер.
Это мои мысли, наверно по некоторым пунктам придется посоветоваться с преподами.

**Comment by iproha94** [comment]
Переделать сингтон на не ленивую инициализацию.

**Comment by d-frolov** [comment]
Мне не понравилось, что в конструкторе конфигуратора давится IO исключение, 
 } catch (IOException e) {
            LOGGER.error(e);
            return;
 }
и сама конфигурация остается недоинициализированной, но при этом с ней продолжают работать. 
Я обычно следую такому подходу:

1. Если есть ошибка в конфигураторе, то сервер не стартует.
2. Наличие конкретного параметра и даже самого файла конфигурации не обязательно (кроме специально оговоренных случаев). Но тогда у параметров везде должны быть дефолты (можно и null, но для параметра должно быть явно указано notnull или nullable).

**Comment by d-frolov** [comment]
Ленивая инициализация синглтона в вашем случае не нужна, так как все равно потом конфигурация грузится первой строчкой. Можно статиком инициализировать. Ну или тогда уж в параметрах указывайте конфиг файл. Но это минорные вещи, по отношению к недоинициализации.

**Comment by iproha94** [comment]
Теперь конфигурация не синглтон (она будет в контексте сервисов)
Все поля обязательны, иначе не стартуем.
Усложнился конструктор конфигурации (много проверок на не null)
