### ISSUE TITLE
GameServices.java

### ISSUE THREAD

**Issue by d-frolov** [iproha94/javaClickerLite#12]
А почему контекст не захотели использовать? В принципе для маленького одномодульного проекта можно конечно и так, но в многомодульном проекте для уменьшения зависимостей лучше сервисы сложить в контекст, и в конструктор GameMechanics не передавать, а тоже использовать сервисы. 

Да и ресурсы хорошо бы тоже обернуть во что-то, может сделать сервисом, который первым из сервисов инициализируется.

**Comment by iproha94** [comment]
просто не успели сделать, теперь все готово
