### ISSUE TITLE
GameMechanics

### ISSUE THREAD

**Issue by d-frolov** [iproha94/javaClickerLite#13]
1. Посмотрите внимательно как у вас инициализируется gMResource и какие могут быть последствия.

**Comment by iproha94** [comment]
Если я правильно понял, то я исправил 
GMResource newGMResource = (GMResource) (resources.get("GMResource"));
gMResource = newGMResource;
на 
 GMResource newGMResource = (GMResource) (resources.get(GMResource.class));
gMResource = newGMResource;
И тогда закрываю issue
