### ISSUE TITLE
Json simple

### ISSUE THREAD

**Issue by d-frolov** [iproha94/javaClickerLite#15]
А вас не раздражают unchecked преобразования при работе с этой библиотекой?

Есть, например, более строгий gson

**Comment by iproha94** [comment]
Перевел всё на gson.
Вся обработка сообщений происходит в классe GameMessager
Когда у JsonObject вызываю getAsString() , то возникают ошибки, поэтому в место этого вызываю toString(). 
Также давлю все инспекции. Там практически все приходится проверять на != null , а при приеме - передаче большого кол-ва сообщений, это может замедлить работу (так мне кажется).
