### ISSUE TITLE
Connection должен закрываться

### ISSUE THREAD

**Issue by KSolovyev** [iproha94/javaClickerLite#17]
Это должно происходить обязательно. Т.е. либо try-with-resource либо try-finally
Тут я вижу два способа:
-либо сделать у TExecutor'а зависимость на DbService
-либо сделать источник Connection'a сервисом-синглтоном

**Comment by iproha94** [comment]
они закрывались в потайном месте))
но в новой репе всё лучше
https://github.com/iproha94/MultiNunja
