### ISSUE TITLE
Интерфейс для страницы со Scores

### ISSUE THREAD

**Issue by KSolovyev** [iproha94/javaClickerLite#19]
Если вы хотите сделать на ней пагинацию, то интерфейс должен быть такой:
```
List<Score> getBunch(int from, int count);
int getCount();
```
Я не очень понял зачем нужен метод получающий n первых записей? Это интерфейс для топ n?

**Comment by Evgeny-Ivanov** [comment]
Да, это требование со стороны Фронтенда

**Comment by iproha94** [comment]
исправили в
https://github.com/iproha94/MultiNunja
